// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using data_access.Data;

#nullable disable

namespace data_access.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("data_access.Entities.CashierShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CashRegisterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosingDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DepositedCash")
                        .HasColumnType("money");

                    b.Property<DateTime>("OpeningDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("WithdrawnCash")
                        .HasColumnType("money");

                    b.Property<int>("WorkShiftId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CashRegisterId");

                    b.HasIndex("WorkShiftId");

                    b.ToTable("CashierShifts");
                });

            modelBuilder.Entity("data_access.Entities.CashRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CashRegisters");
                });

            modelBuilder.Entity("data_access.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Кухня"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Бар"
                        });
                });

            modelBuilder.Entity("data_access.Entities.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<int>("SubcategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Картопля по-селянськи",
                            Price = 65m,
                            SubcategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Картопля з сиром Чеддер",
                            Price = 69m,
                            SubcategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Картопляне пюре",
                            Price = 52m,
                            SubcategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Гречка з грибами",
                            Price = 56m,
                            SubcategoryId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Картопля смажена",
                            Price = 68m,
                            SubcategoryId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Локшина домашня",
                            Price = 52m,
                            SubcategoryId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Тако",
                            Price = 129m,
                            SubcategoryId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Самоса в лаваші",
                            Price = 127m,
                            SubcategoryId = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "Сир по-чешськи",
                            Price = 103m,
                            SubcategoryId = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "Дерун",
                            Price = 125m,
                            SubcategoryId = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "Кров'янка з шукрутом",
                            Price = 117m,
                            SubcategoryId = 2
                        },
                        new
                        {
                            Id = 12,
                            Name = "Ковбаски курячі",
                            Price = 139m,
                            SubcategoryId = 2
                        },
                        new
                        {
                            Id = 13,
                            Name = "Ковбаски свинні",
                            Price = 144m,
                            SubcategoryId = 2
                        },
                        new
                        {
                            Id = 14,
                            Name = "Ковбаски телячі",
                            Price = 148m,
                            SubcategoryId = 2
                        },
                        new
                        {
                            Id = 15,
                            Name = "Асорті ковбас",
                            Price = 463m,
                            SubcategoryId = 2
                        },
                        new
                        {
                            Id = 16,
                            Name = "Картопляні чіпси",
                            Price = 105m,
                            SubcategoryId = 3
                        },
                        new
                        {
                            Id = 17,
                            Name = "Пивна тарілка",
                            Price = 103m,
                            SubcategoryId = 3
                        },
                        new
                        {
                            Id = 18,
                            Name = "М'ясна тарілка до пива",
                            Price = 173m,
                            SubcategoryId = 3
                        },
                        new
                        {
                            Id = 19,
                            Name = "Дошка з пивними закусками",
                            Price = 172m,
                            SubcategoryId = 3
                        },
                        new
                        {
                            Id = 20,
                            Name = "Сирна тарілка",
                            Price = 316m,
                            SubcategoryId = 3
                        },
                        new
                        {
                            Id = 21,
                            Name = "М'ясна тарілка",
                            Price = 172m,
                            SubcategoryId = 3
                        },
                        new
                        {
                            Id = 22,
                            Name = "Дошка з копченостями",
                            Price = 215m,
                            SubcategoryId = 3
                        },
                        new
                        {
                            Id = 23,
                            Name = "Рибна тарілка",
                            Price = 182m,
                            SubcategoryId = 3
                        },
                        new
                        {
                            Id = 24,
                            Name = "Брускети з копченим сомом",
                            Price = 105m,
                            SubcategoryId = 3
                        },
                        new
                        {
                            Id = 25,
                            Name = "Соління",
                            Price = 120m,
                            SubcategoryId = 3
                        },
                        new
                        {
                            Id = 26,
                            Name = "Оселедець",
                            Price = 113m,
                            SubcategoryId = 3
                        },
                        new
                        {
                            Id = 27,
                            Name = "Тартар з яловичини",
                            Price = 186m,
                            SubcategoryId = 3
                        },
                        new
                        {
                            Id = 28,
                            Name = "Борщ український",
                            Price = 119m,
                            SubcategoryId = 4
                        },
                        new
                        {
                            Id = 29,
                            Name = "Бульйон з телятини",
                            Price = 133m,
                            SubcategoryId = 4
                        },
                        new
                        {
                            Id = 30,
                            Name = "Бограч",
                            Price = 119m,
                            SubcategoryId = 4
                        },
                        new
                        {
                            Id = 31,
                            Name = "Грибна юшка",
                            Price = 105m,
                            SubcategoryId = 4
                        },
                        new
                        {
                            Id = 32,
                            Name = "Грецький салат",
                            Price = 120m,
                            SubcategoryId = 5
                        },
                        new
                        {
                            Id = 33,
                            Name = "Салат з копченим язиком",
                            Price = 174m,
                            SubcategoryId = 5
                        },
                        new
                        {
                            Id = 34,
                            Name = "Теплий салат з телятини",
                            Price = 200m,
                            SubcategoryId = 5
                        },
                        new
                        {
                            Id = 35,
                            Name = "Салат із печеним буряком",
                            Price = 93m,
                            SubcategoryId = 5
                        },
                        new
                        {
                            Id = 36,
                            Name = "Салат зі свіжих овочів",
                            Price = 114m,
                            SubcategoryId = 5
                        },
                        new
                        {
                            Id = 37,
                            Name = "Салат Цезар",
                            Price = 157m,
                            SubcategoryId = 5
                        },
                        new
                        {
                            Id = 38,
                            Name = "Салат Оселедець під шубою",
                            Price = 92m,
                            SubcategoryId = 5
                        },
                        new
                        {
                            Id = 39,
                            Name = "Салат з лососем",
                            Price = 226m,
                            SubcategoryId = 5
                        },
                        new
                        {
                            Id = 40,
                            Name = "Салат Мімоза",
                            Price = 92m,
                            SubcategoryId = 5
                        },
                        new
                        {
                            Id = 41,
                            Name = "Салат Олів'є",
                            Price = 119m,
                            SubcategoryId = 5
                        },
                        new
                        {
                            Id = 42,
                            Name = "Креветки у сухарях панко",
                            Price = 238m,
                            SubcategoryId = 6
                        },
                        new
                        {
                            Id = 43,
                            Name = "Стейк з лосося",
                            Price = 442m,
                            SubcategoryId = 6
                        },
                        new
                        {
                            Id = 44,
                            Name = "Мідії у вершковому соусі",
                            Price = 252m,
                            SubcategoryId = 6
                        },
                        new
                        {
                            Id = 45,
                            Name = "Мойва в пивному клярі",
                            Price = 142m,
                            SubcategoryId = 6
                        },
                        new
                        {
                            Id = 46,
                            Name = "Короп по-чеськи",
                            Price = 156m,
                            SubcategoryId = 6
                        },
                        new
                        {
                            Id = 47,
                            Name = "Короп фрі",
                            Price = 76m,
                            SubcategoryId = 6
                        },
                        new
                        {
                            Id = 48,
                            Name = "Копчена річкова форель",
                            Price = 100m,
                            SubcategoryId = 6
                        },
                        new
                        {
                            Id = 49,
                            Name = "Курячі гомілки",
                            Price = 142m,
                            SubcategoryId = 7
                        },
                        new
                        {
                            Id = 50,
                            Name = "Курячі крильця buffalo",
                            Price = 142m,
                            SubcategoryId = 7
                        },
                        new
                        {
                            Id = 51,
                            Name = "Бургер яловичий з картоплею по-селянськи",
                            Price = 215m,
                            SubcategoryId = 7
                        },
                        new
                        {
                            Id = 52,
                            Name = "Підкопчений язик",
                            Price = 221m,
                            SubcategoryId = 7
                        },
                        new
                        {
                            Id = 53,
                            Name = "Куряче філе в беконі",
                            Price = 215m,
                            SubcategoryId = 7
                        },
                        new
                        {
                            Id = 54,
                            Name = "Яловичий медальйон",
                            Price = 330m,
                            SubcategoryId = 7
                        },
                        new
                        {
                            Id = 55,
                            Name = "Перепела",
                            Price = 214m,
                            SubcategoryId = 7
                        },
                        new
                        {
                            Id = 56,
                            Name = "Качина ніжка конфі",
                            Price = 218m,
                            SubcategoryId = 7
                        },
                        new
                        {
                            Id = 57,
                            Name = "Пів качки",
                            Price = 678m,
                            SubcategoryId = 7
                        },
                        new
                        {
                            Id = 58,
                            Name = "Печінка теляча",
                            Price = 169m,
                            SubcategoryId = 7
                        },
                        new
                        {
                            Id = 59,
                            Name = "Телячі щоки з хумусом",
                            Price = 175m,
                            SubcategoryId = 7
                        },
                        new
                        {
                            Id = 60,
                            Name = "Волинський шніцель",
                            Price = 182m,
                            SubcategoryId = 7
                        },
                        new
                        {
                            Id = 61,
                            Name = "Стейк свинний на кістці",
                            Price = 103m,
                            SubcategoryId = 7
                        },
                        new
                        {
                            Id = 62,
                            Name = "Баварські реберця",
                            Price = 254m,
                            SubcategoryId = 7
                        },
                        new
                        {
                            Id = 63,
                            Name = "Дошка з закусками",
                            Price = 787m,
                            SubcategoryId = 7
                        },
                        new
                        {
                            Id = 64,
                            Name = "Рулька свинна",
                            Price = 409m,
                            SubcategoryId = 7
                        },
                        new
                        {
                            Id = 65,
                            Name = "Трюфельний",
                            Price = 36m,
                            SubcategoryId = 8
                        },
                        new
                        {
                            Id = 66,
                            Name = "Пікантний з каррі",
                            Price = 36m,
                            SubcategoryId = 8
                        },
                        new
                        {
                            Id = 67,
                            Name = "Blue Cheese",
                            Price = 36m,
                            SubcategoryId = 8
                        },
                        new
                        {
                            Id = 68,
                            Name = "BBQ",
                            Price = 30m,
                            SubcategoryId = 8
                        },
                        new
                        {
                            Id = 69,
                            Name = "Тартар",
                            Price = 30m,
                            SubcategoryId = 8
                        },
                        new
                        {
                            Id = 70,
                            Name = "Пілатті",
                            Price = 30m,
                            SubcategoryId = 8
                        },
                        new
                        {
                            Id = 71,
                            Name = "Чізкейк",
                            Price = 112m,
                            SubcategoryId = 9
                        },
                        new
                        {
                            Id = 72,
                            Name = "Яблучний штрудель",
                            Price = 89m,
                            SubcategoryId = 9
                        },
                        new
                        {
                            Id = 73,
                            Name = "Creme Brulee",
                            Price = 78m,
                            SubcategoryId = 9
                        },
                        new
                        {
                            Id = 74,
                            Name = "Бананове",
                            Price = 62m,
                            SubcategoryId = 10
                        },
                        new
                        {
                            Id = 75,
                            Name = "Шоколадне",
                            Price = 62m,
                            SubcategoryId = 10
                        },
                        new
                        {
                            Id = 76,
                            Name = "Пломбір",
                            Price = 50m,
                            SubcategoryId = 10
                        },
                        new
                        {
                            Id = 77,
                            Name = "З джемами",
                            Price = 60m,
                            SubcategoryId = 10
                        },
                        new
                        {
                            Id = 78,
                            Name = "Мохіто без алкогольне",
                            Price = 72m,
                            SubcategoryId = 11
                        },
                        new
                        {
                            Id = 79,
                            Name = "Лимонад",
                            Price = 66m,
                            SubcategoryId = 11
                        },
                        new
                        {
                            Id = 80,
                            Name = "Узвар",
                            Price = 80m,
                            SubcategoryId = 11
                        },
                        new
                        {
                            Id = 81,
                            Name = "Боржомі",
                            Price = 66m,
                            SubcategoryId = 11
                        },
                        new
                        {
                            Id = 82,
                            Name = "Моршинська",
                            Price = 33m,
                            SubcategoryId = 11
                        },
                        new
                        {
                            Id = 83,
                            Name = "Pepsi",
                            Price = 47m,
                            SubcategoryId = 11
                        },
                        new
                        {
                            Id = 84,
                            Name = "Сік",
                            Price = 36m,
                            SubcategoryId = 11
                        },
                        new
                        {
                            Id = 85,
                            Name = "Чай класичний",
                            Price = 55m,
                            SubcategoryId = 12
                        },
                        new
                        {
                            Id = 86,
                            Name = "Чай фірмовий",
                            Price = 60m,
                            SubcategoryId = 12
                        },
                        new
                        {
                            Id = 87,
                            Name = "Еспресо",
                            Price = 32m,
                            SubcategoryId = 12
                        },
                        new
                        {
                            Id = 88,
                            Name = "Американо",
                            Price = 32m,
                            SubcategoryId = 12
                        },
                        new
                        {
                            Id = 89,
                            Name = "Капучіно",
                            Price = 38m,
                            SubcategoryId = 12
                        },
                        new
                        {
                            Id = 90,
                            Name = "Лате",
                            Price = 43m,
                            SubcategoryId = 12
                        },
                        new
                        {
                            Id = 91,
                            Name = "Aperol Shpritz",
                            Price = 143m,
                            SubcategoryId = 13
                        },
                        new
                        {
                            Id = 92,
                            Name = "Black Shpritz",
                            Price = 130m,
                            SubcategoryId = 13
                        },
                        new
                        {
                            Id = 93,
                            Name = "Hugo",
                            Price = 142m,
                            SubcategoryId = 13
                        },
                        new
                        {
                            Id = 94,
                            Name = "Bramble",
                            Price = 142m,
                            SubcategoryId = 13
                        },
                        new
                        {
                            Id = 95,
                            Name = "Tommy's Margo",
                            Price = 162m,
                            SubcategoryId = 13
                        },
                        new
                        {
                            Id = 96,
                            Name = "Amaro Sour",
                            Price = 162m,
                            SubcategoryId = 13
                        },
                        new
                        {
                            Id = 97,
                            Name = "Бандерівський Mule",
                            Price = 130m,
                            SubcategoryId = 13
                        },
                        new
                        {
                            Id = 98,
                            Name = "Boulevardier",
                            Price = 142m,
                            SubcategoryId = 13
                        },
                        new
                        {
                            Id = 99,
                            Name = "Sarmatian Negroni",
                            Price = 142m,
                            SubcategoryId = 13
                        },
                        new
                        {
                            Id = 100,
                            Name = "Bloody Mary",
                            Price = 139m,
                            SubcategoryId = 13
                        },
                        new
                        {
                            Id = 101,
                            Name = "В-52",
                            Price = 94m,
                            SubcategoryId = 13
                        },
                        new
                        {
                            Id = 102,
                            Name = "Hop Sour",
                            Price = 125m,
                            SubcategoryId = 13
                        },
                        new
                        {
                            Id = 103,
                            Name = "Tropical Breath",
                            Price = 142m,
                            SubcategoryId = 13
                        },
                        new
                        {
                            Id = 104,
                            Name = "Lychee Sour",
                            Price = 130m,
                            SubcategoryId = 13
                        },
                        new
                        {
                            Id = 105,
                            Name = "Aperol Bridge",
                            Price = 109m,
                            SubcategoryId = 13
                        },
                        new
                        {
                            Id = 106,
                            Name = "Black Elephant",
                            Price = 123m,
                            SubcategoryId = 13
                        },
                        new
                        {
                            Id = 107,
                            Name = "Hiroshima",
                            Price = 106m,
                            SubcategoryId = 13
                        },
                        new
                        {
                            Id = 108,
                            Name = "Дункель",
                            Price = 40m,
                            SubcategoryId = 14
                        },
                        new
                        {
                            Id = 109,
                            Name = "Празьке",
                            Price = 38m,
                            SubcategoryId = 14
                        },
                        new
                        {
                            Id = 110,
                            Name = "Сангушко світле",
                            Price = 42m,
                            SubcategoryId = 14
                        },
                        new
                        {
                            Id = 111,
                            Name = "Бергшлосс світле",
                            Price = 40m,
                            SubcategoryId = 14
                        },
                        new
                        {
                            Id = 112,
                            Name = "Жигулівське",
                            Price = 35m,
                            SubcategoryId = 14
                        },
                        new
                        {
                            Id = 113,
                            Name = "Шардоне (біле)",
                            Price = 72m,
                            SubcategoryId = 15
                        },
                        new
                        {
                            Id = 114,
                            Name = "Совіньйон Блан (біле)",
                            Price = 144m,
                            SubcategoryId = 15
                        },
                        new
                        {
                            Id = 115,
                            Name = "Касал Мендес Віньйон Верде (біле)",
                            Price = 105m,
                            SubcategoryId = 15
                        },
                        new
                        {
                            Id = 116,
                            Name = "Каса дель Коппієре Б’янко (біле)",
                            Price = 84m,
                            SubcategoryId = 15
                        },
                        new
                        {
                            Id = 117,
                            Name = "Каберне (червоне)",
                            Price = 72m,
                            SubcategoryId = 15
                        },
                        new
                        {
                            Id = 118,
                            Name = "К’янті Каватіна (червоне)",
                            Price = 113m,
                            SubcategoryId = 15
                        },
                        new
                        {
                            Id = 119,
                            Name = "Каса дель Коппієре Россо (червоне)",
                            Price = 84m,
                            SubcategoryId = 15
                        },
                        new
                        {
                            Id = 120,
                            Name = "Дорнфельдер (червоне)",
                            Price = 144m,
                            SubcategoryId = 15
                        },
                        new
                        {
                            Id = 121,
                            Name = "Жан Поль Шене Руж (червоне)",
                            Price = 117m,
                            SubcategoryId = 15
                        },
                        new
                        {
                            Id = 122,
                            Name = "Столична",
                            Price = 65m,
                            SubcategoryId = 16
                        },
                        new
                        {
                            Id = 123,
                            Name = "Фінляндія",
                            Price = 77m,
                            SubcategoryId = 16
                        },
                        new
                        {
                            Id = 124,
                            Name = "Немирів Де Люкс",
                            Price = 46m,
                            SubcategoryId = 16
                        },
                        new
                        {
                            Id = 125,
                            Name = "Немирів",
                            Price = 33m,
                            SubcategoryId = 16
                        },
                        new
                        {
                            Id = 126,
                            Name = "Зубрівка Бізон Гранс",
                            Price = 40m,
                            SubcategoryId = 16
                        },
                        new
                        {
                            Id = 127,
                            Name = "Зубрівка Золота",
                            Price = 40m,
                            SubcategoryId = 16
                        },
                        new
                        {
                            Id = 128,
                            Name = "Курвуаз’є V.S.",
                            Price = 250m,
                            SubcategoryId = 17
                        },
                        new
                        {
                            Id = 129,
                            Name = "Курвуаз’є V.S.O.P",
                            Price = 361m,
                            SubcategoryId = 17
                        },
                        new
                        {
                            Id = 130,
                            Name = "Арарат 5*",
                            Price = 97m,
                            SubcategoryId = 17
                        },
                        new
                        {
                            Id = 131,
                            Name = "Болград 5*",
                            Price = 50m,
                            SubcategoryId = 17
                        },
                        new
                        {
                            Id = 132,
                            Name = "Гудаурі 4*",
                            Price = 50m,
                            SubcategoryId = 17
                        },
                        new
                        {
                            Id = 133,
                            Name = "Бехерівка",
                            Price = 76m,
                            SubcategoryId = 18
                        },
                        new
                        {
                            Id = 134,
                            Name = "Єгермейстер",
                            Price = 102m,
                            SubcategoryId = 18
                        },
                        new
                        {
                            Id = 135,
                            Name = "Кампарі",
                            Price = 60m,
                            SubcategoryId = 18
                        },
                        new
                        {
                            Id = 136,
                            Name = "Абсент",
                            Price = 143m,
                            SubcategoryId = 18
                        },
                        new
                        {
                            Id = 137,
                            Name = "Вишнівка",
                            Price = 31m,
                            SubcategoryId = 18
                        },
                        new
                        {
                            Id = 138,
                            Name = "Лісова ягода",
                            Price = 31m,
                            SubcategoryId = 18
                        },
                        new
                        {
                            Id = 139,
                            Name = "Смородинівка",
                            Price = 31m,
                            SubcategoryId = 18
                        },
                        new
                        {
                            Id = 140,
                            Name = "Перцівка",
                            Price = 31m,
                            SubcategoryId = 18
                        },
                        new
                        {
                            Id = 141,
                            Name = "Гленфідіш 15",
                            Price = 308m,
                            SubcategoryId = 19
                        },
                        new
                        {
                            Id = 142,
                            Name = "Джек Деніелс",
                            Price = 135m,
                            SubcategoryId = 19
                        },
                        new
                        {
                            Id = 143,
                            Name = "Блек Лейбл 12",
                            Price = 160m,
                            SubcategoryId = 19
                        },
                        new
                        {
                            Id = 144,
                            Name = "Ред Лейбл",
                            Price = 106m,
                            SubcategoryId = 19
                        },
                        new
                        {
                            Id = 145,
                            Name = "Джемесон",
                            Price = 126m,
                            SubcategoryId = 19
                        },
                        new
                        {
                            Id = 146,
                            Name = "Джим Бім",
                            Price = 110m,
                            SubcategoryId = 19
                        },
                        new
                        {
                            Id = 147,
                            Name = "Бушмілс Оріджинал",
                            Price = 108m,
                            SubcategoryId = 19
                        },
                        new
                        {
                            Id = 148,
                            Name = "Ханкі баністер",
                            Price = 105m,
                            SubcategoryId = 19
                        });
                });

            modelBuilder.Entity("data_access.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PinCode")
                        .HasColumnType("int");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Вікторія Мельник",
                            PinCode = 1234,
                            PositionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Лариса Кописова",
                            PinCode = 6789,
                            PositionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Альберт Бондар",
                            PinCode = 4321,
                            PositionId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ольга Корчик",
                            PinCode = 9876,
                            PositionId = 2
                        });
                });

            modelBuilder.Entity("data_access.Entities.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Halls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Бар"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Основний зал"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Літня тераса"
                        });
                });

            modelBuilder.Entity("data_access.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Closed")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CutleryNumber")
                        .HasColumnType("int")
                        .HasColumnName("Number of cutlery");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Opened")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("money")
                        .HasColumnName("Total amount of money");

                    b.Property<int>("WorkShiftID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("WorkShiftID", "EmployeeID");

                    b.ToTable("Orders");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Order");
                });

            modelBuilder.Entity("data_access.Entities.OrderDish", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "DishId");

                    b.HasIndex("DishId");

                    b.ToTable("OrdersDishes");
                });

            modelBuilder.Entity("data_access.Entities.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrdersStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Відкрите"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Закрите без оплати"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Закрите та оплачене"
                        });
                });

            modelBuilder.Entity("data_access.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PaymentType = "Готівка"
                        },
                        new
                        {
                            Id = 2,
                            PaymentType = "Картка"
                        });
                });

            modelBuilder.Entity("data_access.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Position");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Адміністратор"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Офіціант"
                        });
                });

            modelBuilder.Entity("data_access.Entities.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Subcategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Гарніри"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Гарячі закуски"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Закуски"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Перші страви"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "Салати"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Name = "Риба та морепродукти"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Name = "М'ясо & Птиця"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Name = "Соуси"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Name = "Десерти"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Name = "Морозиво"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Name = "Безалкогольні напої"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Name = "Гарячі напої"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Name = "Коктейлі алкогольні"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Name = "Пиво"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Name = "Вино"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Name = "Горілка"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Name = "Коньяк"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Name = "Настоянки"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Name = "Віскі"
                        });
                });

            modelBuilder.Entity("data_access.Entities.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HallId = 2,
                            Number = "1"
                        },
                        new
                        {
                            Id = 2,
                            HallId = 2,
                            Number = "2"
                        },
                        new
                        {
                            Id = 3,
                            HallId = 2,
                            Number = "3"
                        },
                        new
                        {
                            Id = 4,
                            HallId = 2,
                            Number = "4"
                        },
                        new
                        {
                            Id = 5,
                            HallId = 2,
                            Number = "5"
                        },
                        new
                        {
                            Id = 6,
                            HallId = 2,
                            Number = "6"
                        },
                        new
                        {
                            Id = 7,
                            HallId = 2,
                            Number = "7"
                        },
                        new
                        {
                            Id = 8,
                            HallId = 2,
                            Number = "8"
                        },
                        new
                        {
                            Id = 9,
                            HallId = 2,
                            Number = "9"
                        },
                        new
                        {
                            Id = 10,
                            HallId = 2,
                            Number = "10"
                        },
                        new
                        {
                            Id = 11,
                            HallId = 1,
                            Number = "1"
                        },
                        new
                        {
                            Id = 12,
                            HallId = 1,
                            Number = "2"
                        },
                        new
                        {
                            Id = 13,
                            HallId = 1,
                            Number = "3"
                        },
                        new
                        {
                            Id = 14,
                            HallId = 1,
                            Number = "4"
                        });
                });

            modelBuilder.Entity("data_access.Entities.WorkShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WorkShifts");
                });

            modelBuilder.Entity("data_access.Entities.WorkShiftEmployee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("WorkShiftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeFrom")
                        .HasColumnType("datetime2")
                        .HasColumnName("Time from");

                    b.Property<DateTime?>("TimeTo")
                        .HasColumnType("datetime2")
                        .HasColumnName("Time to");

                    b.HasKey("EmployeeId", "WorkShiftId");

                    b.HasIndex("WorkShiftId");

                    b.ToTable("WorkShiftsEmployees");
                });

            modelBuilder.Entity("data_access.Entities.DeliveryOrder", b =>
                {
                    b.HasBaseType("data_access.Entities.Order");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Client name");

                    b.Property<DateTime>("DeliveryTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Delivery time");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Phone number");

                    b.HasDiscriminator().HasValue("DeliveryOrder");
                });

            modelBuilder.Entity("data_access.Entities.InternalOrder", b =>
                {
                    b.HasBaseType("data_access.Entities.Order");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.HasIndex("TableId");

                    b.HasDiscriminator().HasValue("InternalOrder");
                });

            modelBuilder.Entity("data_access.Entities.CashierShift", b =>
                {
                    b.HasOne("data_access.Entities.CashRegister", "CashRegister")
                        .WithMany("CashierShifts")
                        .HasForeignKey("CashRegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("data_access.Entities.WorkShift", "WorkShift")
                        .WithMany("CashierShifts")
                        .HasForeignKey("WorkShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CashRegister");

                    b.Navigation("WorkShift");
                });

            modelBuilder.Entity("data_access.Entities.Dish", b =>
                {
                    b.HasOne("data_access.Entities.Subcategory", "Subcategory")
                        .WithMany("Dishes")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("data_access.Entities.Employee", b =>
                {
                    b.HasOne("data_access.Entities.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("data_access.Entities.Order", b =>
                {
                    b.HasOne("data_access.Entities.OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("data_access.Entities.Payment", "Payment")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentId");

                    b.HasOne("data_access.Entities.WorkShiftEmployee", "WorkShiftEmployee")
                        .WithMany("Orders")
                        .HasForeignKey("WorkShiftID", "EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderStatus");

                    b.Navigation("Payment");

                    b.Navigation("WorkShiftEmployee");
                });

            modelBuilder.Entity("data_access.Entities.OrderDish", b =>
                {
                    b.HasOne("data_access.Entities.Dish", "Dish")
                        .WithMany("OrderDishes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("data_access.Entities.Order", "Order")
                        .WithMany("OrderDishes")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("data_access.Entities.Subcategory", b =>
                {
                    b.HasOne("data_access.Entities.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("data_access.Entities.Table", b =>
                {
                    b.HasOne("data_access.Entities.Hall", "Hall")
                        .WithMany("Tables")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("data_access.Entities.WorkShiftEmployee", b =>
                {
                    b.HasOne("data_access.Entities.Employee", "Employee")
                        .WithMany("WorkShiftEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("data_access.Entities.WorkShift", "WorkShift")
                        .WithMany("WorkShiftEmployees")
                        .HasForeignKey("WorkShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("WorkShift");
                });

            modelBuilder.Entity("data_access.Entities.InternalOrder", b =>
                {
                    b.HasOne("data_access.Entities.Table", "Table")
                        .WithMany("InternalOrders")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("data_access.Entities.CashRegister", b =>
                {
                    b.Navigation("CashierShifts");
                });

            modelBuilder.Entity("data_access.Entities.Category", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("data_access.Entities.Dish", b =>
                {
                    b.Navigation("OrderDishes");
                });

            modelBuilder.Entity("data_access.Entities.Employee", b =>
                {
                    b.Navigation("WorkShiftEmployees");
                });

            modelBuilder.Entity("data_access.Entities.Hall", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("data_access.Entities.Order", b =>
                {
                    b.Navigation("OrderDishes");
                });

            modelBuilder.Entity("data_access.Entities.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("data_access.Entities.Payment", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("data_access.Entities.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("data_access.Entities.Subcategory", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("data_access.Entities.Table", b =>
                {
                    b.Navigation("InternalOrders");
                });

            modelBuilder.Entity("data_access.Entities.WorkShift", b =>
                {
                    b.Navigation("CashierShifts");

                    b.Navigation("WorkShiftEmployees");
                });

            modelBuilder.Entity("data_access.Entities.WorkShiftEmployee", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
